### ISSUE TITLE
Compiled Script 

### ISSUE THREAD

**Issue by gorfreed** [SmokeyMcBong/StreamDeckClock#1]
I can't believe nobody is asking for this, but would it be possible for you to provide your awesome Stream Deck apps into some format that doesn't require C# or Visual Studio knowledge? Or at least some documentation on what to do with the files? I tried my best to tinker around with it, but I cannot get it working. I know that means I am probably the wrong audience for your work, but I am not a streamer, and more interested in what else you can do with the device - so I would love to use your fancy scripts on my Stream Deck :)

**Comment by SmokeyMcBong** [comment]
Hi and thank you for the kind words, its greatly appreciated! 

To be completely honest I have been focusing a lot on the StreamDeckMonitor project and this project has fell behind quite a bit. 
With the StreamDeckMonitor project I made the structure of it easier for installation and use and also added a small configurator application to make changes on the fly etc without having to edit config files. I am currently in the process of completely re-working StreamDeckClock to bring it up to the same level.

You also brought up a great point about installation and full-use documentation being missing, that completely slipped my mind, thank you for letting me know I will add that to both project Readme files soon. 

For installation of both projects should be a case of downloading the compiled release zip, extracting the zip to a folder somewhere and running StreamDeckClock.exe / StreamDeckMonitor.exe while the Stream Deck Device is on.

For my personal use, I created a new profile using the official Stream Deck Software and set a button to start StreamDeckMonitor.exe and a button to change the profile to another. 
The reason I set a button to change to another profile is because of a limitation with the current API, there is no current way of getting what profile is running and no way to change the actual profile itself. 

So as of now both projects will automatically close itself completely when a button is pressed on the actual device, and clear all keys of images so your left with a blank screen. So its easier to make that button we use to close the application, the one that also changes the profile to another if that makes sense (I have a tendency of making even simple things sound far to complicated than they are)

Here is my personal Stream Deck Device profile for running both projects so you can see what I mean.. 
[StreamDeckApps(streamDeckProfile).zip](https://github.com/SmokeyMcBong/StreamDeckClock/files/1844303/StreamDeckApps.streamDeckProfile.zip)

(middle button is the clock, top right two buttons are the system monitor and configurator app. and bottom right button is a different profile)
Feel free to use/edit if you like, just import the profile and change the location of the applications to where you have them extracted 

Again, thank you so much for your kind words, ideas and interest in these projects!

**Comment by gorfreed** [comment]
Thank you so much for the quick and detailed reply!! :) I am totally fine with editing config files, my machine's problem with StreamDeckMonitor is, that it is unable to execute it, as it immediately prompts "StreamDeckMonitor has stopped working".  I already checked permissions, etc. but without success. Is there something else I can try?

In terms of ideas, I got a bunch - though I am unable to accomplish any of them :) How cool would a NotificationDeck be for example? Basically (through some magic) each button would show the logo of one of the many communication channels that plague us every day (Slack, Jira, Gmail, Todo, Messengers,....) + the current # of unread notifications (that are coming in via Pushbullet or similar). When pressed, the corresponding app is opened and the count reset. For someone like me who has do deal daily with a lot of all-over-the-place project management and remote teams, this would not only be saving a lot of time but also be immensely motivating, since going through your tasks would be kind of like going though the lid  buttons of these old telephones ("barry, you got a call on line 5!")  - total retro-fun instead of the dreadful Chrome tab avalanche ;)

**Comment by SmokeyMcBong** [comment]
A NotificationDeck sounds like a pretty darn cool idea to be honest mate! Will definitely look into that, thank you! :)

Sorry these questions are going to sound very basic but it's just to get an idea as to why these crashes are happening..

-Which version of Windows are you currently running?
-Was the entire zip file (including all subfolders) extracted to a folder?
-Does the Configurator app open correctly?
-Has the folder 'StreamDeckMonitor_v5.3\res\_\generated' been created?
-If your familiar with Event Viewer, is it possible you could paste the error message please?

(the error should be under windows logs/application. Something similar to this..)
![event viewer](https://user-images.githubusercontent.com/1133831/37864479-6697216a-2f67-11e8-8ce0-d87cea64344c.png)


Thanks again for your ideas and input, it really is greatly appreciated! :)

**Comment by gorfreed** [comment]
Dude, awesome!! You get started on the technicalities and I think of a better name for the app, deal?? :D All fun aside, I think Elgato is not really promoting the device to be used for non-streaming purposes as much as they could. I only discovered it last week and i was looking for some programmable productivity  hotkeys since forever! Their competition in that field (mostly "XKeys") is a lot more expensive even without the Optimus-like button screens. There is so much stuff they could do/sell with that (Stream Deck App Store, hello?!!), and a preset for notifications would be clearly one of the most obvious usecases.

I will send you all the infos regarding the crashing executable as soon as i am back home again!

**Comment by gorfreed** [comment]
Hi Mate, here are the answers:
- I am running Windows 10 Pro 1709
- The entire folder was unzipped

![screenshot_20180324211323](https://user-images.githubusercontent.com/6634117/37868546-adbe8b32-2fa8-11e8-8f03-1653253bbbee.png)

- Configurator opens without issues

![screenshot_20180324211348](https://user-images.githubusercontent.com/6634117/37868555-cac37a26-2fa8-11e8-939d-a73d3ff85a4c.png)

- "res_\generated" has not been created

![image](https://user-images.githubusercontent.com/6634117/37868574-13f3ddb2-2fa9-11e8-8f25-a3bdc7e08086.png)

- executing StreamDeckMonitor.exe prompts

![screenshot_20180324211408](https://user-images.githubusercontent.com/6634117/37868583-34eaf56e-2fa9-11e8-9829-f7a2840147e5.png)

Event log says:
Event 1000 - Application Error
Faulting application name: StreamDeckMonitor.exe, version: 5.3.0.0, time stamp: 0x5aafd75f
Faulting module name: KERNELBASE.dll, version: 10.0.16299.309, time stamp: 0xd3aa915c
Exception code: 0xe0434352
Fault offset: 0x001008f2
Faulting process id: 0x3ae8
Faulting application start time: 0x01d3c3aca74f4f70
Faulting application path: H:\StreamDeckMonitor_v5.3 (1)\StreamDeckMonitor.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 482981e4-174f-4955-a620-2e0a8e6b167d
Faulting package full name: 
Faulting package-relative application ID: 

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-03-24T20:14:03.618453000Z" /> 
  <EventRecordID>24689</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Gore</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>StreamDeckMonitor.exe</Data> 
  <Data>5.3.0.0</Data> 
  <Data>5aafd75f</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.16299.309</Data> 
  <Data>d3aa915c</Data> 
  <Data>e0434352</Data> 
  <Data>001008f2</Data> 
  <Data>3ae8</Data> 
  <Data>01d3c3aca74f4f70</Data> 
  <Data>H:\StreamDeckMonitor_v5.3 (1)\StreamDeckMonitor.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>482981e4-174f-4955-a620-2e0a8e6b167d</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by SmokeyMcBong** [comment]
Hi mate, thank you for all the info and sorry for the delay

I have done a little testing here and there and I think I have an idea as to why this crash is happening..

Do you currently have the [MSI Afterburner application](http://www.guru3d.com/files-details/msi-afterburner-beta-download.html) installed on that system?
(as the community library used in this project pulls its information from the program/service itself quietly in the background)

If this is the case I will add this to the documentation (which is next on my agenda lol) 
and maybe add an option to the configurator app to enable or disable frame rate monitoring so not forced to download and install external apps (MSI Afterburner) if not necessary?

**Comment by gorfreed** [comment]
Hey there! Sorry for the late reply!
Unfortunately, installing Afterburner did not solve the issue. Executing StreamDeckMonitor.exe still prompts the same error! There is a small change though: The Image Layout for StreamDeckMonitor partially loads on the device (you can see two "CPU" images) - but that's it. 
How about this: Could you compile the executable for StreamDeckClock, so I can try to run it? That way we can rule out possible dependencies with MSI Afterburner! 

PS: I am pins and needles for implementations with notification badges!! :D I imagine objects on a grid (looking very much like the iOS icon grid) being toggled via e.g. the Pushover API:

![image](https://user-images.githubusercontent.com/6634117/38069153-30690584-3315-11e8-8eb6-de5993f38b8d.png)

**Comment by SmokeyMcBong** [comment]
Hi mate, do the previous releases of StreamDeckClock experience the same crash upon start-up? I can compile another build but I'm sure I haven't changed anything with that project since the last release, if that executable crashes on start-up also then my problem is more deeply rooted than I thought :-( 
I will have a look into the pushover api, sounds pretty useful for this type of project

**Comment by gorfreed** [comment]
StreamDeckClock still doesn't have an exe though! :) I am incapable of getting code magic run in a programming tool, remember? :D

**Comment by d-rez** [comment]
@gorfreed it does, download it from the releases section

https://github.com/SmokeyMcBong/StreamDeckClock/releases/tag/v1.5 

In my case it causes 100% CPU usage, both downloaded and compiled on my own so doesn't seem like I'll be using this.

Cool project concept though

**Comment by SmokeyMcBong** [comment]
I'm sorry for my absence, I will not be able to continue ANY projects for the foreseeable future.
Unfortunately my last remaining family member is terminally ill and will be continuing to look after her until the end. Then comes finding new work, new home etc after that

Thanks again for your interest in these little projects, i'm sorry that I cannot continue them for now

Take care

SmokeyMcBong

**Comment by gorfreed** [comment]
Smokey, I wish you all the strength in the world for the road ahead!!

**Comment by SmokeyMcBong** [comment]
I have had a little time here and there and have updated StreamDeckMonitor to have a much better optimised clock feature as well as its own configurator app etc.

https://github.com/SmokeyMcBong/StreamDeckMonitor

StreamDeckClock is now EOL and StreamDeckMonitor will take its place with more features etc
